---
# tasks file for htop

- name: Install htop (debian group only)
  apt:
    name:
      - htop
    state: latest
  when: "'debian' in group_names"

- name: Install htop (amazon-linux group only)
  yum:
    name: htop
    state: latest
  when: "'amazon-linux' in group_names"

- name: Copy over the htop configuration file
  copy:
    src: htoprc
    dest: /etc/htoprc
