---
# tasks file for htop

# This is required temporarily, because of
# https://github.com/ansible/ansible/issues/56583
- name: Temporary workaround for ansible/ansible#56583
  set_fact:
    ansible_facts:
      pkg_mgr: yum
  when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
- name: Install htop
  package:
    name: htop

- name: Copy over the htop configuration file
  copy:
    src: htoprc
    dest: /etc/htoprc
